/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.net.HttpURLConnection;
import java.net.URL;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void grabsDifferentQuote() {
      String quote1 = App.getaQuote(0);
        System.out.println(quote1);
      String quote2 = App.getaQuote(1);
        System.out.println(quote2);

      assertNotEquals(quote1,quote2);
    }

    @Test void checkConnection() throws IOException {
        URL url = new URL("http://swquotesapi.digitaljedi.dk/api/SWQuote/RandomStarWarsQuote");

        HttpURLConnection sut = App.urlConnector();

        assertEquals("GET", sut.getRequestMethod());
    }
}
